---
title: "homework 2"
output: github_document
---

1.	You cannot just get data from a few different cities and run the regression of crime rate on number of police officers in a city to understand how more cops in the streets affect crime because correlation is different from causation. Any correlation we find with this regression does not tell us any direction of causation. With the data, we cannot differentiate between a larger police presence causing crime or more crime causing a larger police presence. High crime cities have an incentive to hire more cops so it is likely the result would be a positive correlation between crime and police. Found that when extra police were there for terrorist reasons. This is a way to established a causal relationship in this area. 
2.	The researches from the University of Pennsylvania were able to isolate this effect by looking at an example in Washington D.C. They needed to find an example where there is a large amount of police in an area for reasons unrelated to crime. When there is a high risk of terrorism (orange) in D.C., there is an increased police presence by law. Total daily crime decreases on these orange-alert days, we see this with the negative coefficient on high alert that is statistically significant at the 5% level. 
3.	They had to control for Metro ridership because of the fewer tourist hypothesis. This was trying to capture the lower ridership on the Metro (people not going out when there is a higher risk) and the lower crime (unrelated to more police). Still controlling for this, there is larger amounts of police is negatively related to crime. 
4.	From Table 4, we are looking at if high alert days impact the amount of crime differently in different areas of Washington D.C. The authors use interactions between the high-alert and the location. District 1 (the most likely location of potential terrorism so the most police officers) is the only location where the impact is notable. In other districts, we see the impact as negative or even nonexistent (zero).      
